#!/bin/sh

rm -rf .rev \
&& gulp build \
&& cd .rev \
&& git init \
&& git checkout -b gh-pages \
&& echo "turtle_pools.p2p.ninja" > CNAME \
&& git add . \
&& git commit -m ".rev" \
&& git remote add origin git@github.com:blakelapierre/turtle_pools \
&& git fetch origin \
&& git rebase -s ours origin/gh-pages \
&& git push origin gh-pages