#!/bin/sh

gulp build \
&& cd .dev \
&& git init \
&& git checkout -b gh-pages \
&& git add . \
&& git commit -m ".dev" \
&& git remote add origin git@github.com:blakelapierre/turtle_pools \
&& git push origin :gh-pages \
&& git push origin gh-pages